##################################################
##  hic configuration file.                     ##
## Use this file to customize your hic analysis ##
##################################################

################
## Basic options 
# R1 and R2 suffix 
R1_SUFFIX: _R1.fastq.bz2
R2_SUFFIX: _R2.fastq.bz2
SAMPLES: HiC_D00  # sample names 
GENOME: hg19   # genome build
N_CPUS : 12  #number of CPUs
RES_ENZYME:  GATC  # restriction enzyme. 
BIN_SIZE: 50000  #bin size for calculating DI and insulation.
BIN_NUM: 40 # number of bins to calculate DI TADs. 
#EMAIL: shz254@ucsd.edu  #

